# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from omni_driver/OmniButtonEvent.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class OmniButtonEvent(genpy.Message):
  _md5sum = "67ad876972cf46727cadcf266dde0b5c"
  _type = "omni_driver/OmniButtonEvent"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool grey_button
bool white_button
bool grey_button_clicked
bool white_button_clicked
"""
  __slots__ = ['grey_button','white_button','grey_button_clicked','white_button_clicked']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       grey_button,white_button,grey_button_clicked,white_button_clicked

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OmniButtonEvent, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.grey_button is None:
        self.grey_button = False
      if self.white_button is None:
        self.white_button = False
      if self.grey_button_clicked is None:
        self.grey_button_clicked = False
      if self.white_button_clicked is None:
        self.white_button_clicked = False
    else:
      self.grey_button = False
      self.white_button = False
      self.grey_button_clicked = False
      self.white_button_clicked = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.grey_button, _x.white_button, _x.grey_button_clicked, _x.white_button_clicked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.grey_button, _x.white_button, _x.grey_button_clicked, _x.white_button_clicked,) = _get_struct_4B().unpack(str[start:end])
      self.grey_button = bool(self.grey_button)
      self.white_button = bool(self.white_button)
      self.grey_button_clicked = bool(self.grey_button_clicked)
      self.white_button_clicked = bool(self.white_button_clicked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.grey_button, _x.white_button, _x.grey_button_clicked, _x.white_button_clicked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.grey_button, _x.white_button, _x.grey_button_clicked, _x.white_button_clicked,) = _get_struct_4B().unpack(str[start:end])
      self.grey_button = bool(self.grey_button)
      self.white_button = bool(self.white_button)
      self.grey_button_clicked = bool(self.grey_button_clicked)
      self.white_button_clicked = bool(self.white_button_clicked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
