// Generated by gencpp from file iiwa_driver/AdditionalOutputs.msg
// DO NOT EDIT!


#ifndef IIWA_DRIVER_MESSAGE_ADDITIONALOUTPUTS_H
#define IIWA_DRIVER_MESSAGE_ADDITIONALOUTPUTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/Float64MultiArray.h>

namespace iiwa_driver
{
template <class ContainerAllocator>
struct AdditionalOutputs_
{
  typedef AdditionalOutputs_<ContainerAllocator> Type;

  AdditionalOutputs_()
    : header()
    , external_torques()
    , commanded_torques()
    , commanded_positions()  {
    }
  AdditionalOutputs_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , external_torques(_alloc)
    , commanded_torques(_alloc)
    , commanded_positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _external_torques_type;
  _external_torques_type external_torques;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _commanded_torques_type;
  _commanded_torques_type commanded_torques;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _commanded_positions_type;
  _commanded_positions_type commanded_positions;





  typedef boost::shared_ptr< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> const> ConstPtr;

}; // struct AdditionalOutputs_

typedef ::iiwa_driver::AdditionalOutputs_<std::allocator<void> > AdditionalOutputs;

typedef boost::shared_ptr< ::iiwa_driver::AdditionalOutputs > AdditionalOutputsPtr;
typedef boost::shared_ptr< ::iiwa_driver::AdditionalOutputs const> AdditionalOutputsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator1> & lhs, const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.external_torques == rhs.external_torques &&
    lhs.commanded_torques == rhs.commanded_torques &&
    lhs.commanded_positions == rhs.commanded_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator1> & lhs, const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iiwa_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c34331d511e328461cf6e053cfded8c";
  }

  static const char* value(const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c34331d511e3284ULL;
  static const uint64_t static_value2 = 0x61cf6e053cfded8cULL;
};

template<class ContainerAllocator>
struct DataType< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iiwa_driver/AdditionalOutputs";
  }

  static const char* value(const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Float64MultiArray external_torques\n"
"std_msgs/Float64MultiArray commanded_torques\n"
"std_msgs/Float64MultiArray commanded_positions\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.external_torques);
      stream.next(m.commanded_torques);
      stream.next(m.commanded_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AdditionalOutputs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iiwa_driver::AdditionalOutputs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iiwa_driver::AdditionalOutputs_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "external_torques: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.external_torques);
    s << indent << "commanded_torques: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.commanded_torques);
    s << indent << "commanded_positions: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.commanded_positions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IIWA_DRIVER_MESSAGE_ADDITIONALOUTPUTS_H
