// Generated by gencpp from file iiwa_tools/GetFKResponse.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETFKRESPONSE_H
#define IIWA_TOOLS_MESSAGE_GETFKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace iiwa_tools
{
template <class ContainerAllocator>
struct GetFKResponse_
{
  typedef GetFKResponse_<ContainerAllocator> Type;

  GetFKResponse_()
    : poses()  {
    }
  GetFKResponse_(const ContainerAllocator& _alloc)
    : poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::iiwa_tools::GetFKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iiwa_tools::GetFKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFKResponse_

typedef ::iiwa_tools::GetFKResponse_<std::allocator<void> > GetFKResponse;

typedef boost::shared_ptr< ::iiwa_tools::GetFKResponse > GetFKResponsePtr;
typedef boost::shared_ptr< ::iiwa_tools::GetFKResponse const> GetFKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iiwa_tools::GetFKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iiwa_tools::GetFKResponse_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetFKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iiwa_tools::GetFKResponse_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetFKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iiwa_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetFKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetFKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetFKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db8ce58a1deaf0d1f2e7fdd257963e81";
  }

  static const char* value(const ::iiwa_tools::GetFKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb8ce58a1deaf0d1ULL;
  static const uint64_t static_value2 = 0xf2e7fdd257963e81ULL;
};

template<class ContainerAllocator>
struct DataType< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iiwa_tools/GetFKResponse";
  }

  static const char* value(const ::iiwa_tools::GetFKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::iiwa_tools::GetFKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iiwa_tools::GetFKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iiwa_tools::GetFKResponse_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETFKRESPONSE_H
