// Generated by gencpp from file iiwa_tools/GetFK.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETFK_H
#define IIWA_TOOLS_MESSAGE_GETFK_H

#include <ros/service_traits.h>


#include <iiwa_tools/GetFKRequest.h>
#include <iiwa_tools/GetFKResponse.h>


namespace iiwa_tools
{

struct GetFK
{

typedef GetFKRequest Request;
typedef GetFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFK
} // namespace iiwa_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_tools::GetFK > {
  static const char* value()
  {
    return "c0251d878bff4e1536417b78314d82f5";
  }

  static const char* value(const ::iiwa_tools::GetFK&) { return value(); }
};

template<>
struct DataType< ::iiwa_tools::GetFK > {
  static const char* value()
  {
    return "iiwa_tools/GetFK";
  }

  static const char* value(const ::iiwa_tools::GetFK&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_tools::GetFKRequest> should match
// service_traits::MD5Sum< ::iiwa_tools::GetFK >
template<>
struct MD5Sum< ::iiwa_tools::GetFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetFK >::value();
  }
  static const char* value(const ::iiwa_tools::GetFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetFKRequest> should match
// service_traits::DataType< ::iiwa_tools::GetFK >
template<>
struct DataType< ::iiwa_tools::GetFKRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetFK >::value();
  }
  static const char* value(const ::iiwa_tools::GetFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_tools::GetFKResponse> should match
// service_traits::MD5Sum< ::iiwa_tools::GetFK >
template<>
struct MD5Sum< ::iiwa_tools::GetFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetFK >::value();
  }
  static const char* value(const ::iiwa_tools::GetFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetFKResponse> should match
// service_traits::DataType< ::iiwa_tools::GetFK >
template<>
struct DataType< ::iiwa_tools::GetFKResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetFK >::value();
  }
  static const char* value(const ::iiwa_tools::GetFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETFK_H
