// Generated by gencpp from file iiwa_tools/GetGravityResponse.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETGRAVITYRESPONSE_H
#define IIWA_TOOLS_MESSAGE_GETGRAVITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iiwa_tools
{
template <class ContainerAllocator>
struct GetGravityResponse_
{
  typedef GetGravityResponse_<ContainerAllocator> Type;

  GetGravityResponse_()
    : compensation_torques()  {
    }
  GetGravityResponse_(const ContainerAllocator& _alloc)
    : compensation_torques(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _compensation_torques_type;
  _compensation_torques_type compensation_torques;





  typedef boost::shared_ptr< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetGravityResponse_

typedef ::iiwa_tools::GetGravityResponse_<std::allocator<void> > GetGravityResponse;

typedef boost::shared_ptr< ::iiwa_tools::GetGravityResponse > GetGravityResponsePtr;
typedef boost::shared_ptr< ::iiwa_tools::GetGravityResponse const> GetGravityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iiwa_tools::GetGravityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iiwa_tools::GetGravityResponse_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetGravityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.compensation_torques == rhs.compensation_torques;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iiwa_tools::GetGravityResponse_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetGravityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iiwa_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "923d65fbe90dce06205c35e62126536a";
  }

  static const char* value(const ::iiwa_tools::GetGravityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x923d65fbe90dce06ULL;
  static const uint64_t static_value2 = 0x205c35e62126536aULL;
};

template<class ContainerAllocator>
struct DataType< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iiwa_tools/GetGravityResponse";
  }

  static const char* value(const ::iiwa_tools::GetGravityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] compensation_torques\n"
;
  }

  static const char* value(const ::iiwa_tools::GetGravityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.compensation_torques);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGravityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iiwa_tools::GetGravityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iiwa_tools::GetGravityResponse_<ContainerAllocator>& v)
  {
    s << indent << "compensation_torques[]" << std::endl;
    for (size_t i = 0; i < v.compensation_torques.size(); ++i)
    {
      s << indent << "  compensation_torques[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.compensation_torques[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETGRAVITYRESPONSE_H
