// Generated by gencpp from file iiwa_tools/GetGravity.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETGRAVITY_H
#define IIWA_TOOLS_MESSAGE_GETGRAVITY_H

#include <ros/service_traits.h>


#include <iiwa_tools/GetGravityRequest.h>
#include <iiwa_tools/GetGravityResponse.h>


namespace iiwa_tools
{

struct GetGravity
{

typedef GetGravityRequest Request;
typedef GetGravityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGravity
} // namespace iiwa_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_tools::GetGravity > {
  static const char* value()
  {
    return "3da8875e9eeb07327815c7e1e6ef0f85";
  }

  static const char* value(const ::iiwa_tools::GetGravity&) { return value(); }
};

template<>
struct DataType< ::iiwa_tools::GetGravity > {
  static const char* value()
  {
    return "iiwa_tools/GetGravity";
  }

  static const char* value(const ::iiwa_tools::GetGravity&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_tools::GetGravityRequest> should match
// service_traits::MD5Sum< ::iiwa_tools::GetGravity >
template<>
struct MD5Sum< ::iiwa_tools::GetGravityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetGravity >::value();
  }
  static const char* value(const ::iiwa_tools::GetGravityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetGravityRequest> should match
// service_traits::DataType< ::iiwa_tools::GetGravity >
template<>
struct DataType< ::iiwa_tools::GetGravityRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetGravity >::value();
  }
  static const char* value(const ::iiwa_tools::GetGravityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_tools::GetGravityResponse> should match
// service_traits::MD5Sum< ::iiwa_tools::GetGravity >
template<>
struct MD5Sum< ::iiwa_tools::GetGravityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetGravity >::value();
  }
  static const char* value(const ::iiwa_tools::GetGravityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetGravityResponse> should match
// service_traits::DataType< ::iiwa_tools::GetGravity >
template<>
struct DataType< ::iiwa_tools::GetGravityResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetGravity >::value();
  }
  static const char* value(const ::iiwa_tools::GetGravityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETGRAVITY_H
