// Generated by gencpp from file iiwa_tools/GetIKResponse.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETIKRESPONSE_H
#define IIWA_TOOLS_MESSAGE_GETIKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace iiwa_tools
{
template <class ContainerAllocator>
struct GetIKResponse_
{
  typedef GetIKResponse_<ContainerAllocator> Type;

  GetIKResponse_()
    : joints()
    , accepted_tolerance()
    , is_valid()  {
    }
  GetIKResponse_(const ContainerAllocator& _alloc)
    : joints(_alloc)
    , accepted_tolerance(_alloc)
    , is_valid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _joints_type;
  _joints_type joints;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _accepted_tolerance_type;
  _accepted_tolerance_type accepted_tolerance;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _is_valid_type;
  _is_valid_type is_valid;





  typedef boost::shared_ptr< ::iiwa_tools::GetIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iiwa_tools::GetIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIKResponse_

typedef ::iiwa_tools::GetIKResponse_<std::allocator<void> > GetIKResponse;

typedef boost::shared_ptr< ::iiwa_tools::GetIKResponse > GetIKResponsePtr;
typedef boost::shared_ptr< ::iiwa_tools::GetIKResponse const> GetIKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iiwa_tools::GetIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iiwa_tools::GetIKResponse_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetIKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints &&
    lhs.accepted_tolerance == rhs.accepted_tolerance &&
    lhs.is_valid == rhs.is_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iiwa_tools::GetIKResponse_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetIKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iiwa_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3e928e318e2d510381df70b3943ee9e";
  }

  static const char* value(const ::iiwa_tools::GetIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3e928e318e2d510ULL;
  static const uint64_t static_value2 = 0x381df70b3943ee9eULL;
};

template<class ContainerAllocator>
struct DataType< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iiwa_tools/GetIKResponse";
  }

  static const char* value(const ::iiwa_tools::GetIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# joints[i]      == joint angle solution for each pose_state[i]\n"
"std_msgs/Float64MultiArray joints\n"
"float64[] accepted_tolerance\n"
"bool[] is_valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::iiwa_tools::GetIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
      stream.next(m.accepted_tolerance);
      stream.next(m.is_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iiwa_tools::GetIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iiwa_tools::GetIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
    s << indent << "accepted_tolerance[]" << std::endl;
    for (size_t i = 0; i < v.accepted_tolerance.size(); ++i)
    {
      s << indent << "  accepted_tolerance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.accepted_tolerance[i]);
    }
    s << indent << "is_valid[]" << std::endl;
    for (size_t i = 0; i < v.is_valid.size(); ++i)
    {
      s << indent << "  is_valid[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.is_valid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETIKRESPONSE_H
