// Generated by gencpp from file iiwa_tools/GetIK.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETIK_H
#define IIWA_TOOLS_MESSAGE_GETIK_H

#include <ros/service_traits.h>


#include <iiwa_tools/GetIKRequest.h>
#include <iiwa_tools/GetIKResponse.h>


namespace iiwa_tools
{

struct GetIK
{

typedef GetIKRequest Request;
typedef GetIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIK
} // namespace iiwa_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_tools::GetIK > {
  static const char* value()
  {
    return "365217ef42b72f30ced052640d9bbe85";
  }

  static const char* value(const ::iiwa_tools::GetIK&) { return value(); }
};

template<>
struct DataType< ::iiwa_tools::GetIK > {
  static const char* value()
  {
    return "iiwa_tools/GetIK";
  }

  static const char* value(const ::iiwa_tools::GetIK&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_tools::GetIKRequest> should match
// service_traits::MD5Sum< ::iiwa_tools::GetIK >
template<>
struct MD5Sum< ::iiwa_tools::GetIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetIK >::value();
  }
  static const char* value(const ::iiwa_tools::GetIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetIKRequest> should match
// service_traits::DataType< ::iiwa_tools::GetIK >
template<>
struct DataType< ::iiwa_tools::GetIKRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetIK >::value();
  }
  static const char* value(const ::iiwa_tools::GetIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_tools::GetIKResponse> should match
// service_traits::MD5Sum< ::iiwa_tools::GetIK >
template<>
struct MD5Sum< ::iiwa_tools::GetIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetIK >::value();
  }
  static const char* value(const ::iiwa_tools::GetIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetIKResponse> should match
// service_traits::DataType< ::iiwa_tools::GetIK >
template<>
struct DataType< ::iiwa_tools::GetIKResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetIK >::value();
  }
  static const char* value(const ::iiwa_tools::GetIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETIK_H
