// Generated by gencpp from file iiwa_tools/GetJacobians.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETJACOBIANS_H
#define IIWA_TOOLS_MESSAGE_GETJACOBIANS_H

#include <ros/service_traits.h>


#include <iiwa_tools/GetJacobiansRequest.h>
#include <iiwa_tools/GetJacobiansResponse.h>


namespace iiwa_tools
{

struct GetJacobians
{

typedef GetJacobiansRequest Request;
typedef GetJacobiansResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJacobians
} // namespace iiwa_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_tools::GetJacobians > {
  static const char* value()
  {
    return "7cd7b210d0e70924367a510d05e781d4";
  }

  static const char* value(const ::iiwa_tools::GetJacobians&) { return value(); }
};

template<>
struct DataType< ::iiwa_tools::GetJacobians > {
  static const char* value()
  {
    return "iiwa_tools/GetJacobians";
  }

  static const char* value(const ::iiwa_tools::GetJacobians&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_tools::GetJacobiansRequest> should match
// service_traits::MD5Sum< ::iiwa_tools::GetJacobians >
template<>
struct MD5Sum< ::iiwa_tools::GetJacobiansRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetJacobians >::value();
  }
  static const char* value(const ::iiwa_tools::GetJacobiansRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetJacobiansRequest> should match
// service_traits::DataType< ::iiwa_tools::GetJacobians >
template<>
struct DataType< ::iiwa_tools::GetJacobiansRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetJacobians >::value();
  }
  static const char* value(const ::iiwa_tools::GetJacobiansRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_tools::GetJacobiansResponse> should match
// service_traits::MD5Sum< ::iiwa_tools::GetJacobians >
template<>
struct MD5Sum< ::iiwa_tools::GetJacobiansResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_tools::GetJacobians >::value();
  }
  static const char* value(const ::iiwa_tools::GetJacobiansResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_tools::GetJacobiansResponse> should match
// service_traits::DataType< ::iiwa_tools::GetJacobians >
template<>
struct DataType< ::iiwa_tools::GetJacobiansResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_tools::GetJacobians >::value();
  }
  static const char* value(const ::iiwa_tools::GetJacobiansResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETJACOBIANS_H
