// Generated by gencpp from file iiwa_tools/GetMassMatrixRequest.msg
// DO NOT EDIT!


#ifndef IIWA_TOOLS_MESSAGE_GETMASSMATRIXREQUEST_H
#define IIWA_TOOLS_MESSAGE_GETMASSMATRIXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iiwa_tools
{
template <class ContainerAllocator>
struct GetMassMatrixRequest_
{
  typedef GetMassMatrixRequest_<ContainerAllocator> Type;

  GetMassMatrixRequest_()
    : joint_angles()  {
    }
  GetMassMatrixRequest_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_angles_type;
  _joint_angles_type joint_angles;





  typedef boost::shared_ptr< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMassMatrixRequest_

typedef ::iiwa_tools::GetMassMatrixRequest_<std::allocator<void> > GetMassMatrixRequest;

typedef boost::shared_ptr< ::iiwa_tools::GetMassMatrixRequest > GetMassMatrixRequestPtr;
typedef boost::shared_ptr< ::iiwa_tools::GetMassMatrixRequest const> GetMassMatrixRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator1> & lhs, const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iiwa_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eebf9cc7d525d143ad033b65dacb648";
  }

  static const char* value(const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eebf9cc7d525d14ULL;
  static const uint64_t static_value2 = 0x3ad033b65dacb648ULL;
};

template<class ContainerAllocator>
struct DataType< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iiwa_tools/GetMassMatrixRequest";
  }

  static const char* value(const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_angles\n"
;
  }

  static const char* value(const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMassMatrixRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iiwa_tools::GetMassMatrixRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IIWA_TOOLS_MESSAGE_GETMASSMATRIXREQUEST_H
