// Generated by gencpp from file omni_driver/OmniButtonEvent.msg
// DO NOT EDIT!


#ifndef OMNI_DRIVER_MESSAGE_OMNIBUTTONEVENT_H
#define OMNI_DRIVER_MESSAGE_OMNIBUTTONEVENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omni_driver
{
template <class ContainerAllocator>
struct OmniButtonEvent_
{
  typedef OmniButtonEvent_<ContainerAllocator> Type;

  OmniButtonEvent_()
    : grey_button(false)
    , white_button(false)
    , grey_button_clicked(false)
    , white_button_clicked(false)  {
    }
  OmniButtonEvent_(const ContainerAllocator& _alloc)
    : grey_button(false)
    , white_button(false)
    , grey_button_clicked(false)
    , white_button_clicked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _grey_button_type;
  _grey_button_type grey_button;

   typedef uint8_t _white_button_type;
  _white_button_type white_button;

   typedef uint8_t _grey_button_clicked_type;
  _grey_button_clicked_type grey_button_clicked;

   typedef uint8_t _white_button_clicked_type;
  _white_button_clicked_type white_button_clicked;





  typedef boost::shared_ptr< ::omni_driver::OmniButtonEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omni_driver::OmniButtonEvent_<ContainerAllocator> const> ConstPtr;

}; // struct OmniButtonEvent_

typedef ::omni_driver::OmniButtonEvent_<std::allocator<void> > OmniButtonEvent;

typedef boost::shared_ptr< ::omni_driver::OmniButtonEvent > OmniButtonEventPtr;
typedef boost::shared_ptr< ::omni_driver::OmniButtonEvent const> OmniButtonEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omni_driver::OmniButtonEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::omni_driver::OmniButtonEvent_<ContainerAllocator1> & lhs, const ::omni_driver::OmniButtonEvent_<ContainerAllocator2> & rhs)
{
  return lhs.grey_button == rhs.grey_button &&
    lhs.white_button == rhs.white_button &&
    lhs.grey_button_clicked == rhs.grey_button_clicked &&
    lhs.white_button_clicked == rhs.white_button_clicked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::omni_driver::OmniButtonEvent_<ContainerAllocator1> & lhs, const ::omni_driver::OmniButtonEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace omni_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omni_driver::OmniButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omni_driver::OmniButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omni_driver::OmniButtonEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67ad876972cf46727cadcf266dde0b5c";
  }

  static const char* value(const ::omni_driver::OmniButtonEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67ad876972cf4672ULL;
  static const uint64_t static_value2 = 0x7cadcf266dde0b5cULL;
};

template<class ContainerAllocator>
struct DataType< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omni_driver/OmniButtonEvent";
  }

  static const char* value(const ::omni_driver::OmniButtonEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool grey_button\n"
"bool white_button\n"
"bool grey_button_clicked\n"
"bool white_button_clicked\n"
;
  }

  static const char* value(const ::omni_driver::OmniButtonEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grey_button);
      stream.next(m.white_button);
      stream.next(m.grey_button_clicked);
      stream.next(m.white_button_clicked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OmniButtonEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omni_driver::OmniButtonEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omni_driver::OmniButtonEvent_<ContainerAllocator>& v)
  {
    s << indent << "grey_button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.grey_button);
    s << indent << "white_button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.white_button);
    s << indent << "grey_button_clicked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.grey_button_clicked);
    s << indent << "white_button_clicked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.white_button_clicked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNI_DRIVER_MESSAGE_OMNIBUTTONEVENT_H
