// Generated by gencpp from file geomagic_control/DeviceButtonEvent.msg
// DO NOT EDIT!


#ifndef GEOMAGIC_CONTROL_MESSAGE_DEVICEBUTTONEVENT_H
#define GEOMAGIC_CONTROL_MESSAGE_DEVICEBUTTONEVENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace geomagic_control
{
template <class ContainerAllocator>
struct DeviceButtonEvent_
{
  typedef DeviceButtonEvent_<ContainerAllocator> Type;

  DeviceButtonEvent_()
    : grey_button(0)
    , white_button(0)  {
    }
  DeviceButtonEvent_(const ContainerAllocator& _alloc)
    : grey_button(0)
    , white_button(0)  {
  (void)_alloc;
    }



   typedef int32_t _grey_button_type;
  _grey_button_type grey_button;

   typedef int32_t _white_button_type;
  _white_button_type white_button;





  typedef boost::shared_ptr< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> const> ConstPtr;

}; // struct DeviceButtonEvent_

typedef ::geomagic_control::DeviceButtonEvent_<std::allocator<void> > DeviceButtonEvent;

typedef boost::shared_ptr< ::geomagic_control::DeviceButtonEvent > DeviceButtonEventPtr;
typedef boost::shared_ptr< ::geomagic_control::DeviceButtonEvent const> DeviceButtonEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator1> & lhs, const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator2> & rhs)
{
  return lhs.grey_button == rhs.grey_button &&
    lhs.white_button == rhs.white_button;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator1> & lhs, const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace geomagic_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb77877e6b639935c3360838062f05f0";
  }

  static const char* value(const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb77877e6b639935ULL;
  static const uint64_t static_value2 = 0xc3360838062f05f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geomagic_control/DeviceButtonEvent";
  }

  static const char* value(const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 grey_button\n"
"int32 white_button\n"
;
  }

  static const char* value(const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grey_button);
      stream.next(m.white_button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeviceButtonEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geomagic_control::DeviceButtonEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geomagic_control::DeviceButtonEvent_<ContainerAllocator>& v)
  {
    s << indent << "grey_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grey_button);
    s << indent << "white_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.white_button);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEOMAGIC_CONTROL_MESSAGE_DEVICEBUTTONEVENT_H
