// Generated by gencpp from file geomagic_control/DeviceFeedback.msg
// DO NOT EDIT!


#ifndef GEOMAGIC_CONTROL_MESSAGE_DEVICEFEEDBACK_H
#define GEOMAGIC_CONTROL_MESSAGE_DEVICEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace geomagic_control
{
template <class ContainerAllocator>
struct DeviceFeedback_
{
  typedef DeviceFeedback_<ContainerAllocator> Type;

  DeviceFeedback_()
    : force()
    , position()
    , lock()  {
    }
  DeviceFeedback_(const ContainerAllocator& _alloc)
    : force(_alloc)
    , position(_alloc)
    , lock(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _lock_type;
  _lock_type lock;





  typedef boost::shared_ptr< ::geomagic_control::DeviceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geomagic_control::DeviceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DeviceFeedback_

typedef ::geomagic_control::DeviceFeedback_<std::allocator<void> > DeviceFeedback;

typedef boost::shared_ptr< ::geomagic_control::DeviceFeedback > DeviceFeedbackPtr;
typedef boost::shared_ptr< ::geomagic_control::DeviceFeedback const> DeviceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geomagic_control::DeviceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::geomagic_control::DeviceFeedback_<ContainerAllocator1> & lhs, const ::geomagic_control::DeviceFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.force == rhs.force &&
    lhs.position == rhs.position &&
    lhs.lock == rhs.lock;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::geomagic_control::DeviceFeedback_<ContainerAllocator1> & lhs, const ::geomagic_control::DeviceFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace geomagic_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geomagic_control::DeviceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geomagic_control::DeviceFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geomagic_control::DeviceFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94755b031db27fe99c2c235c0da9b072";
  }

  static const char* value(const ::geomagic_control::DeviceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94755b031db27fe9ULL;
  static const uint64_t static_value2 = 0x9c2c235c0da9b072ULL;
};

template<class ContainerAllocator>
struct DataType< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geomagic_control/DeviceFeedback";
  }

  static const char* value(const ::geomagic_control::DeviceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is the force as estimated from the applied torques as well as the current\n"
"# end effector position of the robot arm                           \n"
"geometry_msgs/Vector3  force                                                                  \n"
"geometry_msgs/Vector3  position \n"
"bool[] lock \n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::geomagic_control::DeviceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.position);
      stream.next(m.lock);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeviceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geomagic_control::DeviceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geomagic_control::DeviceFeedback_<ContainerAllocator>& v)
  {
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "lock[]" << std::endl;
    for (size_t i = 0; i < v.lock.size(); ++i)
    {
      s << indent << "  lock[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.lock[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEOMAGIC_CONTROL_MESSAGE_DEVICEFEEDBACK_H
